In [1]:
import numpy as np

In [2]:
#function 1 arange
a =np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [72]:
#function 2 reshape
b= a.reshape(3,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [51]:
#function 3
b.ndim 

2

In [52]:
#function 4
a.dtype

dtype('int32')

In [53]:
#function 5
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [55]:
#function 6
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [56]:
#function 7
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
#function 8
np.empty((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [65]:
#function 9
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [69]:
#function 10
a.shape
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [78]:
#function 11
def f(x,y):
    return 10*x+y
b = np.fromfunction(f,(5,4),dtype=int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [86]:
#function 12
a= np.array([[1,2,3],[4,5,6]])
b= np.array([[7,8,9],[10,11,12]])
np.column_stack((a,b))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [87]:
#function 13
np.hstack((a,b)) 

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [88]:
#function 14
from numpy import newaxis
a[:,newaxis]

array([[[1, 2, 3]],

       [[4, 5, 6]]])

In [89]:
#function 15
np.column_stack is np.hstack

False

In [90]:
#function 16
np.row_stack is np.vstack

True

In [91]:
#function 17
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [96]:
#function 18
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [99]:
#function 19
e = np.full((2,2),7)
e

array([[7, 7],
       [7, 7]])

In [101]:
#function 20
f = np.eye(2)
f

array([[1., 0.],
       [0., 1.]])

In [102]:
#function 21
np.random.random((2,2))

array([[0.11080963, 0.71464452],
       [0.83850355, 0.61273926]])

In [145]:
#function 22
np.save('myArray.txt',a)

In [106]:
#function 23
np.savez('myArray.npz',a,b)

In [107]:
#function 24
np.load('myArray.npy')

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
#function 25
np.add(a,b)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [109]:
#function 26
np.subtract(a,b)

array([[-6, -6, -6],
       [-6, -6, -6]])

In [110]:
#function 27
np.divide(a,b)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [111]:
#function 28
np.multiply(a,b)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [112]:
#function 29
np.exp(a)

array([[  2.71828183,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [113]:
#function 30
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [114]:
#function 31
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ]])

In [115]:
#function 32
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [116]:
#function 33
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [117]:
#function 34
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619]])

In [120]:
#function 35
e.dot(f)

array([[7., 7.],
       [7., 7.]])

In [121]:
#function 36
np.array_equal(a,b)

False

In [123]:
#function 37
np.sort(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [124]:
#function 38
np.std(b)

1.707825127659933

In [125]:
#function 39
np.mean(a)

3.5

In [133]:
#function 40
np.max(a)

6

In [134]:
#function 41
np.min(a)

1

In [135]:
#function 42
np.median(a)

3.5

In [136]:
#function 43
np.corrcoef(a)

array([[1., 1.],
       [1., 1.]])

In [137]:
#function 44
np.info(a)

class:  ndarray
shape:  (2, 3)
strides:  (12, 4)
itemsize:  4
aligned:  True
contiguous:  True
fortran:  False
data pointer: 0x1ece4c378a0
byteorder:  little
byteswap:  False
type: int32


In [138]:
#function 45
np.transpose(a)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [139]:
#function 46
np.append(e,f)

array([7., 7., 7., 7., 1., 0., 0., 1.])

In [141]:
#function 47
np.insert(a,1,5)

array([1, 5, 2, 3, 4, 5, 6])

In [142]:
#function 48
np.delete(a,[1])

array([1, 3, 4, 5, 6])

In [143]:
#function 49
np.cumsum(a)

array([ 1,  3,  6, 10, 15, 21], dtype=int32)

In [152]:
#function 50
d = np.array([[1,2,],[3,4]])
np.savetxt('Array.txt',d)

In [153]:
np.loadtxt('Array.txt')

array([[1., 2.],
       [3., 4.]])